export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_CLOTHING = 'CREATE_CLOTHING';
export const FETCH_CLOTHINGS = 'FETCH_CLOTHINGS';
export const FETCH_CLOTHING = 'FETCH_CLOTHING';
export const DELETE_CLOTHING = 'DELETE_CLOTHING';
export const EDIT_CLOTHING = 'EDIT_CLOTHING';
